### ISSUE TITLE
BURP now adds timezone to timestamps

### ISSUE THREAD

**Issue by qm2k** [qm2k/bbts#6]
(See https://github.com/grke/burp/issues/564 .) Will most likely break our code, and needs supporting in any case.

**Comment by pablodav** [comment]
Hi @qm2k ,

I was planning to add this script in https://github.com/CoffeeITWorks/ansible_burp2_server/issues/9 

But now looking in the status of it, I found this bug.

I'm not sure if it is safe to go with latest stable and this script, should I wait to have this bug resolved?

**Comment by qm2k** [comment]
Haven't tested with the latest stable indeed, but I'll try to look into it this weekend...
